//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALLERY_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GALLERY_LIST()
        {
            this.PICTURE_LIST = new HashSet<PICTURE_LIST>();
        }
    
        public int ID { get; set; }
        public int Gallery_Number { get; set; }
        public string Gallery_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PICTURE_LIST> PICTURE_LIST { get; set; }
    }
}
