//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE_LIST
    {
        public int ID { get; set; }
        public int Gallery_ID { get; set; }
        public int Picture_Number { get; set; }
        public string Description { get; set; }
        public string Mini_Version { get; set; }
        public string Full_Version { get; set; }
    
        public virtual GALLERY_LIST GALLERY_LIST { get; set; }
    }
}
